---
id: 201711-decentralized-governance
base_name: 201711-decentralized-governance
tags:
- rabbit
- microservices
- decentralized governance
presentation_date: 2017-12-01
version: 2017.11.09.1
licenses:
- MIT
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Giovanni Sakti
  email: giosakti@gmail.com
  rubygems_user: giosakti
  slideshare_user:
  speaker_deck_user: giosakti 
